// Code generated by "/var/folders/rn/01jw11855z3bb_vh99hyxrmr0000gn/T/go-build645048251/b001/exe/main go.foss.tools/generate/fopt/example Config -w options.go"
package example

// Option defines an functional option to populate Config
type Option func(s *Config)

// Options defines a plural set of Option
type Options []Option

func (opts Options) apply(s *Config) Config {
    for _, opt := range opts {
        opt(s)
    }
    return *s
}

func Name(value string) Option {
    return func(s *Config) {
        s.Name = value
    }
}


func Value(value string) Option {
    return func(s *Config) {
        s.Value = value
    }
}


func Names(values ...string) Option {
    return func(s *Config) {
        s.Names = append(s.Names, values...)
    }
}


func WithCustom(value Custom) Option {
    return func(s *Config) {
        s.Custom = value
    }
}


func Many(values ...Custom) Option {
    return func(s *Config) {
        s.Many = append(s.Many, values...)
    }
}


